import type { DashboardProject } from "@/features/projects/project-types";

const previewTime = "2026-07-25T07:00:00.000Z";

export const previewProjects: DashboardProject[] = [
  {
    accountId: "preview-a",
    projectRef: "aether-prod",
    name: "Aether Production",
    organizationId: "northstar",
    organizationName: "Northstar Labs",
    organizationPlan: "Free",
    region: "East US (North Virginia)",
    cloudProvider: "AWS",
    rawStatus: "ACTIVE_HEALTHY",
    lifecycleStatus: "active",
    healthStatus: "healthy",
    lastSeenAt: previewTime,
    accountLabel: "Founder",
    accountEmail: "founder@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  {
    accountId: "preview-b",
    projectRef: "atlas-staging",
    name: "Atlas Staging",
    organizationId: "shipyard",
    organizationName: "Shipyard Studio",
    organizationPlan: "Free",
    region: "Central EU (Frankfurt)",
    cloudProvider: "AWS",
    rawStatus: "INACTIVE",
    lifecycleStatus: "paused",
    healthStatus: "unknown",
    lastSeenAt: previewTime,
    accountLabel: "Studio",
    accountEmail: "studio@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  {
    accountId: "preview-a",
    projectRef: "beacon-api",
    name: "Beacon API",
    organizationId: "northstar",
    organizationName: "Northstar Labs",
    organizationPlan: "Free",
    region: "Southeast Asia (Singapore)",
    cloudProvider: "AWS",
    rawStatus: "ACTIVE_UNHEALTHY",
    lifecycleStatus: "active",
    healthStatus: "unhealthy",
    lastSeenAt: previewTime,
    accountLabel: "Founder",
    accountEmail: "founder@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  {
    accountId: "preview-c",
    projectRef: "canvas-web",
    name: "Canvas Web",
    organizationId: "personal",
    organizationName: "Personal",
    organizationPlan: "Free",
    region: "West US (Oregon)",
    cloudProvider: "AWS",
    rawStatus: "RESTORING",
    lifecycleStatus: "transitioning",
    healthStatus: "unknown",
    lastSeenAt: previewTime,
    accountLabel: "Personal",
    accountEmail: "me@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  {
    accountId: "preview-b",
    projectRef: "dockyard-data",
    name: "Dockyard Data",
    organizationId: "shipyard",
    organizationName: "Shipyard Studio",
    organizationPlan: "Free",
    region: "Central EU (Frankfurt)",
    cloudProvider: "AWS",
    rawStatus: "INACTIVE",
    lifecycleStatus: "paused",
    healthStatus: "unknown",
    lastSeenAt: previewTime,
    accountLabel: "Studio",
    accountEmail: "studio@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  {
    accountId: "preview-c",
    projectRef: "ember-notes",
    name: "Ember Notes",
    organizationId: "personal",
    organizationName: "Personal",
    organizationPlan: "Free",
    region: "South Asia (Mumbai)",
    cloudProvider: "AWS",
    rawStatus: "ACTIVE_HEALTHY",
    lifecycleStatus: "active",
    healthStatus: "healthy",
    lastSeenAt: previewTime,
    accountLabel: "Personal",
    accountEmail: "me@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
  ...[
    ["Fjord Analytics", "fjord-analytics", "Founder", "Northstar Labs"],
    ["Grove CRM", "grove-crm", "Personal", "Personal"],
    ["Harbor Docs", "harbor-docs", "Studio", "Shipyard Studio"],
    ["Iris Mobile", "iris-mobile", "Founder", "Northstar Labs"],
    ["Juniper Queue", "juniper-queue", "Personal", "Personal"],
  ].map(
    ([name, projectRef, accountLabel, organizationName], index) =>
      ({
        accountId:
          accountLabel === "Founder"
            ? "preview-a"
            : accountLabel === "Studio"
              ? "preview-b"
              : "preview-c",
        projectRef,
        name,
        organizationId: organizationName.toLowerCase().replaceAll(" ", "-"),
        organizationName,
        organizationPlan: "Free",
        region: index % 2 ? "West EU (London)" : "East US (North Virginia)",
        cloudProvider: "AWS",
        rawStatus: "ACTIVE_HEALTHY",
        lifecycleStatus: "active",
        healthStatus: "healthy",
        lastSeenAt: previewTime,
        accountLabel,
        accountEmail:
          accountLabel === "Founder"
            ? "founder@example.com"
            : accountLabel === "Studio"
              ? "studio@example.com"
              : "me@example.com",
        accountLastSuccessfulSyncAt: previewTime,
      }) satisfies DashboardProject,
  ),
  {
    accountId: "preview-c",
    projectRef: "keel-sandbox",
    name: "Keel Sandbox",
    organizationId: "personal",
    organizationName: "Personal",
    organizationPlan: "Free",
    region: "South Asia (Mumbai)",
    cloudProvider: "AWS",
    rawStatus: "INACTIVE",
    lifecycleStatus: "paused",
    healthStatus: "unknown",
    lastSeenAt: previewTime,
    accountLabel: "Personal",
    accountEmail: "me@example.com",
    accountLastSuccessfulSyncAt: previewTime,
  },
];
